# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-30 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='categorvid',
            new_name='categoryid',
        ),
    ]
