# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-01 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='categorvid',
            new_name='categoryid',
        ),
    ]
