# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='o_goods_price',
            field=models.FloatField(default=0),
        ),
    ]
