# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('u_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='a_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
    ]
