# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=24)),
                ('c_method', models.CharField(max_length=10)),
                ('c_url', models.CharField(max_length=256)),
                ('c_data', models.CharField(max_length=1000)),
                ('c_code', models.CharField(max_length=24)),
                ('c_result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='c_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Module'),
        ),
    ]
