# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
