# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200420_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c_header',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
