# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16)),
                ('c_gril_num', models.IntegerField(default=5)),
                ('c_boy_num', models.IntegerField(default=3)),
            ],
        ),
    ]
